# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-17 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='answers',
            field=models.CharField(default='EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE', max_length=120),
        ),
    ]
