# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-21 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0002_studentmark_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='re_answers',
            field=models.CharField(default='ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ', max_length=120),
        ),
    ]
