# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-22 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetest', '0005_remove_studentmark_re_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmark',
            name='answers',
            field=models.CharField(default='555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555', max_length=120),
        ),
    ]
